version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: hackaton_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: isy_automation
    ports:
      - "5432:5432"
    volumes:
      # Mantém os dados salvos na sua máquina (na pasta oculta .pgdata)
      - .pgdata:/var/lib/postgresql/data
      # Injeta o script SQL para criar o banco e as tabelas automaticamente
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - isy-network

networks:
  isy-network:
    driver: bridge